/**
 * About Page - Video Venture Launch
 * 
 * Author: JP + 2024-12-19
 * 
 * Comprehensive about page featuring solution architecture, purpose, 
 * agentic AI flow design, and dynamic release details.
 */

import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  ArrowLeft, 
  Sparkles, 
  Brain, 
  Zap, 
  Target, 
  Users, 
  Globe, 
  Rocket,
  GitBranch,
  Calendar,
  CheckCircle,
  Clock,
  Code,
  Database,
  Shield,
  Cpu
} from 'lucide-react';

interface ReleaseInfo {
  version: string;
  date: string;
  status: string;
  completion: string;
  features: string[];
  nextMilestone: string;
  lastUpdated?: string;
}

const AboutPage: React.FC = () => {
  const navigate = useNavigate();
  const [releaseInfo, setReleaseInfo] = useState<ReleaseInfo | null>(null);

  // Load dynamic release information
  useEffect(() => {
    // Try to load dynamic release info generated by `make release`
    const loadReleaseInfo = async () => {
      try {
        const { currentRelease } = await import('../data/releaseInfo');
        setReleaseInfo(currentRelease);
      } catch (error) {
        // Fallback to static release info if dynamic file not found
        console.log('Using fallback release info (run `make release` to generate dynamic info)');
        const fallbackReleaseInfo: ReleaseInfo = {
          version: "v0.8.0-beta",
          date: "2024-12-19",
          status: "MVP-Ready",
          completion: "80%",
          features: [
            "UI Design Consistency System",
            "Comprehensive API Client with TypeScript",
            "Backend ADK Integration (Production-Ready)",
            "52 API Tests (Campaign API: 100% passing)",
            "Professional Development Workflow",
            "About Page with Dynamic Release Info"
          ],
          nextMilestone: "Frontend-Backend Integration",
          lastUpdated: "Static fallback data"
        };
        setReleaseInfo(fallbackReleaseInfo);
      }
    };
    
    loadReleaseInfo();
  }, []);

  const architectureComponents = [
    {
      name: "Marketing Orchestrator",
      description: "Central AI agent coordinating the entire campaign creation workflow",
      icon: <Brain className="w-8 h-8 text-blue-400" />,
      type: "Core Agent"
    },
    {
      name: "Business Analysis Agent",
      description: "Analyzes URLs, documents, and business context for campaign insights",
      icon: <Target className="w-8 h-8 text-green-400" />,
      type: "Specialized Agent"
    },
    {
      name: "Content Generation Agent",
      description: "Creates platform-specific social media content with AI optimization",
      icon: <Zap className="w-8 h-8 text-purple-400" />,
      type: "Specialized Agent"
    },
    {
      name: "Campaign Management API",
      description: "FastAPI backend with comprehensive CRUD operations and validation",
      icon: <Database className="w-8 h-8 text-orange-400" />,
      type: "Backend Service"
    },
    {
      name: "React Frontend",
      description: "Modern UI with TypeScript, Tailwind CSS, and glassmorphism design",
      icon: <Code className="w-8 h-8 text-cyan-400" />,
      type: "Frontend Service"
    },
    {
      name: "Google ADK Framework",
      description: "Agent Development Kit providing the foundation for AI agent orchestration",
      icon: <Cpu className="w-8 h-8 text-red-400" />,
      type: "AI Framework"
    }
  ];

  const workflowSteps = [
    {
      step: 1,
      title: "Campaign Setup",
      description: "User provides business context via URLs, files, or manual input",
      agent: "Marketing Orchestrator",
      duration: "30 seconds"
    },
    {
      step: 2,
      title: "Business Analysis",
      description: "AI analyzes business context, extracts key insights and brand voice",
      agent: "Business Analysis Agent",
      duration: "60 seconds"
    },
    {
      step: 3,
      title: "Ideation Phase",
      description: "Generate campaign ideas based on objectives and business context",
      agent: "Marketing Orchestrator",
      duration: "45 seconds"
    },
    {
      step: 4,
      title: "Content Creation",
      description: "Create platform-specific content with hashtags and optimization",
      agent: "Content Generation Agent",
      duration: "90 seconds"
    },
    {
      step: 5,
      title: "Review & Finalize",
      description: "User reviews, edits, and approves generated campaign content",
      agent: "User Interface",
      duration: "2-5 minutes"
    }
  ];

  const keyFeatures = [
    {
      icon: <Brain className="w-6 h-6 text-blue-400" />,
      title: "Agentic AI Architecture",
      description: "Sequential agents working together using Google's ADK framework"
    },
    {
      icon: <Zap className="w-6 h-6 text-purple-400" />,
      title: "5-Minute Campaign Creation",
      description: "Reduce campaign creation time from days to minutes"
    },
    {
      icon: <Globe className="w-6 h-6 text-green-400" />,
      title: "Multi-Platform Content",
      description: "Optimized content for Facebook, Instagram, Twitter, LinkedIn, TikTok"
    },
    {
      icon: <Target className="w-6 h-6 text-orange-400" />,
      title: "Business Context Analysis",
      description: "AI-powered analysis of websites, documents, and brand materials"
    },
    {
      icon: <Users className="w-6 h-6 text-cyan-400" />,
      title: "Audience Optimization",
      description: "Content tailored to specific target audiences and demographics"
    },
    {
      icon: <Shield className="w-6 h-6 text-red-400" />,
      title: "Production-Ready",
      description: "Comprehensive testing, error handling, and scalable architecture"
    }
  ];

  return (
    <div className="min-h-screen vvl-gradient-bg">
      {/* Header */}
      <header className="vvl-header-blur">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-gradient-to-r from-blue-500 to-purple-600 rounded-lg flex items-center justify-center">
                <Sparkles className="w-6 h-6 text-white" />
              </div>
              <div>
                <h1 className="text-xl font-bold vvl-text-primary">About Video Venture Launch</h1>
                <p className="text-xs vvl-text-secondary">Solution Architecture & Release Information</p>
              </div>
            </div>
            <button 
              className="vvl-button-secondary flex items-center gap-1"
              onClick={() => navigate('/')}
            >
              <ArrowLeft size={16} />
              <span>Back to Home</span>
            </button>
          </div>
        </div>
      </header>

      <div className="container mx-auto px-4 py-8">
        {/* Hero Section */}
        <section className="text-center mb-16">
          <div className="vvl-card p-8 max-w-4xl mx-auto">
            <h1 className="text-4xl font-bold vvl-text-primary mb-4">
              The Modern AI Marketing Platform
            </h1>
            <p className="text-xl vvl-text-secondary mb-6 leading-relaxed">
              Video Venture Launch is an agentic AI-powered marketing campaign generator that transforms 
              your marketing workflow. Built with Google's ADK framework and Gemini AI, we reduce 
              campaign creation time from days to minutes.
            </p>
            <div className="flex items-center justify-center gap-2 text-blue-400">
              <Sparkles className="w-5 h-5" />
              <span className="font-medium">Powered by Google's ADK & Gemini AI</span>
            </div>
          </div>
        </section>

        {/* Purpose & Vision */}
        <section className="mb-16">
          <div className="vvl-card p-8">
            <h2 className="text-3xl font-bold vvl-text-primary mb-6 flex items-center gap-3">
              <Rocket className="w-8 h-8 text-blue-400" />
              Purpose & Vision
            </h2>
            <div className="grid md:grid-cols-2 gap-8">
              <div>
                <h3 className="text-xl font-semibold vvl-text-primary mb-3">Our Mission</h3>
                <p className="vvl-text-secondary leading-relaxed mb-4">
                  To democratize professional marketing by making AI-powered campaign creation 
                  accessible to businesses of all sizes. We believe every business deserves 
                  high-quality marketing content without the traditional time and cost barriers.
                </p>
                <h3 className="text-xl font-semibold vvl-text-primary mb-3">Core Value Proposition</h3>
                <ul className="vvl-text-secondary space-y-2">
                  <li className="flex items-center gap-2">
                    <CheckCircle className="w-4 h-4 text-green-400" />
                    Reduce campaign creation from 2-5 days to 5-10 minutes
                  </li>
                  <li className="flex items-center gap-2">
                    <CheckCircle className="w-4 h-4 text-green-400" />
                    Generate platform-optimized content automatically
                  </li>
                  <li className="flex items-center gap-2">
                    <CheckCircle className="w-4 h-4 text-green-400" />
                    Maintain brand consistency across all platforms
                  </li>
                  <li className="flex items-center gap-2">
                    <CheckCircle className="w-4 h-4 text-green-400" />
                    Scale marketing efforts without proportional cost increase
                  </li>
                </ul>
              </div>
              <div>
                <h3 className="text-xl font-semibold vvl-text-primary mb-3">Target Users</h3>
                <div className="space-y-4">
                  <div className="bg-white/5 p-4 rounded-lg">
                    <h4 className="font-medium vvl-text-primary">Small Business Owners</h4>
                    <p className="text-sm vvl-text-secondary">Need professional marketing but lack resources for agencies</p>
                  </div>
                  <div className="bg-white/5 p-4 rounded-lg">
                    <h4 className="font-medium vvl-text-primary">Marketing Teams</h4>
                    <p className="text-sm vvl-text-secondary">Want to scale content creation and improve efficiency</p>
                  </div>
                  <div className="bg-white/5 p-4 rounded-lg">
                    <h4 className="font-medium vvl-text-primary">Startups</h4>
                    <p className="text-sm vvl-text-secondary">Need rapid market entry with limited marketing expertise</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Key Features */}
        <section className="mb-16">
          <div className="vvl-card p-8">
            <h2 className="text-3xl font-bold vvl-text-primary mb-8 flex items-center gap-3">
              <Zap className="w-8 h-8 text-purple-400" />
              Key Features
            </h2>
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
              {keyFeatures.map((feature, index) => (
                <div key={index} className="bg-white/5 p-6 rounded-lg hover:bg-white/10 transition-all duration-200">
                  <div className="flex items-center gap-3 mb-3">
                    {feature.icon}
                    <h3 className="font-semibold vvl-text-primary">{feature.title}</h3>
                  </div>
                  <p className="text-sm vvl-text-secondary">{feature.description}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Solution Architecture */}
        <section className="mb-16">
          <div className="vvl-card p-8">
            <h2 className="text-3xl font-bold vvl-text-primary mb-8 flex items-center gap-3">
              <Cpu className="w-8 h-8 text-blue-400" />
              Solution Architecture
            </h2>
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 mb-8">
              {architectureComponents.map((component, index) => (
                <div key={index} className="bg-white/5 p-6 rounded-lg border border-white/10">
                  <div className="flex items-center gap-3 mb-3">
                    {component.icon}
                    <div>
                      <h3 className="font-semibold vvl-text-primary">{component.name}</h3>
                      <span className="text-xs vvl-text-secondary">{component.type}</span>
                    </div>
                  </div>
                  <p className="text-sm vvl-text-secondary">{component.description}</p>
                </div>
              ))}
            </div>
            
            <div className="bg-white/5 p-6 rounded-lg">
              <h3 className="text-xl font-semibold vvl-text-primary mb-4">Technology Stack</h3>
              <div className="grid md:grid-cols-2 gap-6">
                <div>
                  <h4 className="font-medium vvl-text-primary mb-2">Frontend</h4>
                  <ul className="text-sm vvl-text-secondary space-y-1">
                    <li>• React 18 with TypeScript</li>
                    <li>• Vite for build tooling</li>
                    <li>• Tailwind CSS for styling</li>
                    <li>• Axios for API communication</li>
                    <li>• React Router for navigation</li>
                  </ul>
                </div>
                <div>
                  <h4 className="font-medium vvl-text-primary mb-2">Backend</h4>
                  <ul className="text-sm vvl-text-secondary space-y-1">
                    <li>• Python with FastAPI</li>
                    <li>• Google ADK Framework</li>
                    <li>• Gemini 2.0 Flash Exp</li>
                    <li>• Pytest for testing</li>
                    <li>• Uvicorn ASGI server</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Agentic AI Workflow */}
        <section className="mb-16">
          <div className="vvl-card p-8">
            <h2 className="text-3xl font-bold vvl-text-primary mb-8 flex items-center gap-3">
              <Brain className="w-8 h-8 text-green-400" />
              Agentic AI Workflow
            </h2>
            <p className="vvl-text-secondary mb-8 text-center">
              Our sequential agent architecture orchestrates specialized AI agents to deliver 
              comprehensive marketing campaigns in under 5 minutes.
            </p>
            
            <div className="space-y-6">
              {workflowSteps.map((step, index) => (
                <div key={index} className="flex items-start gap-4 bg-white/5 p-6 rounded-lg">
                  <div className="w-12 h-12 bg-gradient-to-r from-blue-500 to-purple-600 rounded-full flex items-center justify-center flex-shrink-0">
                    <span className="text-lg font-bold text-white">{step.step}</span>
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center gap-4 mb-2">
                      <h3 className="text-lg font-semibold vvl-text-primary">{step.title}</h3>
                      <span className="text-xs bg-blue-500/20 text-blue-300 px-2 py-1 rounded">
                        {step.agent}
                      </span>
                      <span className="text-xs vvl-text-secondary flex items-center gap-1">
                        <Clock className="w-3 h-3" />
                        {step.duration}
                      </span>
                    </div>
                    <p className="vvl-text-secondary">{step.description}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Current Release Information */}
        <section className="mb-16">
          <div className="vvl-card p-8">
            <h2 className="text-3xl font-bold vvl-text-primary mb-8 flex items-center gap-3">
              <GitBranch className="w-8 h-8 text-orange-400" />
              Current Release Information
            </h2>
            
            {releaseInfo && (
              <div className="grid md:grid-cols-2 gap-8">
                <div>
                  <div className="bg-white/5 p-6 rounded-lg mb-6">
                    <h3 className="text-xl font-semibold vvl-text-primary mb-4">Release Status</h3>
                    <div className="space-y-3">
                      <div className="flex justify-between">
                        <span className="vvl-text-secondary">Version:</span>
                        <span className="vvl-text-primary font-medium">{releaseInfo.version}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="vvl-text-secondary">Release Date:</span>
                        <span className="vvl-text-primary font-medium">{releaseInfo.date}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="vvl-text-secondary">Status:</span>
                        <span className="text-green-400 font-medium">{releaseInfo.status}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="vvl-text-secondary">Completion:</span>
                        <span className="text-blue-400 font-medium">{releaseInfo.completion}</span>
                      </div>
                      {releaseInfo.lastUpdated && (
                        <div className="flex justify-between">
                          <span className="vvl-text-secondary">Last Updated:</span>
                          <span className="text-gray-400 font-medium text-xs">{releaseInfo.lastUpdated}</span>
                        </div>
                      )}
                    </div>
                  </div>
                  
                  <div className="bg-white/5 p-6 rounded-lg">
                    <h3 className="text-xl font-semibold vvl-text-primary mb-4">Next Milestone</h3>
                    <p className="vvl-text-secondary">{releaseInfo.nextMilestone}</p>
                  </div>
                </div>
                
                <div>
                  <div className="bg-white/5 p-6 rounded-lg">
                    <h3 className="text-xl font-semibold vvl-text-primary mb-4">Latest Features</h3>
                    <ul className="space-y-2">
                      {releaseInfo.features.map((feature, index) => (
                        <li key={index} className="flex items-center gap-2 vvl-text-secondary">
                          <CheckCircle className="w-4 h-4 text-green-400 flex-shrink-0" />
                          {feature}
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              </div>
            )}
            
            <div className="mt-8 p-4 bg-blue-500/10 border border-blue-500/20 rounded-lg">
              <p className="text-sm vvl-text-secondary text-center">
                <span className="vvl-text-primary font-medium">Note:</span> Release information is updated 
                automatically when running <code className="bg-white/10 px-2 py-1 rounded text-blue-300">make release</code> command.
              </p>
            </div>
          </div>
        </section>

        {/* Call to Action */}
        <section className="text-center">
          <div className="vvl-card p-8">
            <h2 className="text-3xl font-bold vvl-text-primary mb-4">Ready to Transform Your Marketing?</h2>
            <p className="text-xl vvl-text-secondary mb-8">
              Experience the power of agentic AI marketing and create your first campaign in under 5 minutes.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <button 
                className="vvl-button-primary text-lg px-8 py-4 flex items-center gap-2 justify-center"
                onClick={() => navigate('/new-campaign')}
              >
                <Rocket className="w-5 h-5" />
                Create Your Campaign
              </button>
              <button 
                className="vvl-button-secondary text-lg px-8 py-4 flex items-center gap-2 justify-center"
                onClick={() => navigate('/campaigns')}
              >
                <Calendar className="w-5 h-5" />
                View Examples
              </button>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
};

export default AboutPage; 