// Auto-generated release information - Updated: Sat Jun 14 23:40:29 BST 2025
// Generated by 'make release' command

export interface ReleaseInfo {
  version: string;
  date: string;
  status: string;
  completion: string;
  features: string[];
  nextMilestone: string;
  lastUpdated: string;
}

export const currentRelease: ReleaseInfo = {
  version: "v0.8.0-beta",
  date: "2025-06-14",
  status: "MVP-Ready",
  completion: "80%",
  features: [
    "UI Design Consistency System",
    "Comprehensive API Client with TypeScript",
    "Backend ADK Integration (Production-Ready)",
    "52 API Tests (Campaign API: 100% passing)",
    "Professional Development Workflow",
    "About Page with Dynamic Release Info",
    "Enhanced Makefile with Release Management"
  ],
  nextMilestone: "Frontend-Backend Integration",
  lastUpdated: ""
};
